name: Build and deploy Python app to Azure Web App - helenlearnsnepali

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r purplelyrics/requirements.txt

      - name: Copy startup.sh to workspace root
        run: |
          cp purplelyrics/startup.sh .

      - name: Zip only contents (flatten structure)
        run: |
          cd purplelyrics
          zip -r ../release.zip .
          cd ..
          zip -g release.zip startup.sh

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip release.zip
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BAFD0CF2650B492A95E1C7C78B25499A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EB682AB4A67C46E1BE42D6E2738F4B99 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7D57B413D1594EE38CE8C17A4369D3A1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'helenlearnsnepali'
          slot-name: 'Production'
